
title: "abaltra"
author: "Alejandro Baltra"
description: "Sometimes I write stuff. It's not that often though &#1F643;"
permalink: /:title/
lang: "en"
encoding: "utf-8"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true               # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: true           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}

external:                    # see http://fontawesome.com/icons
  - {title: Main Website, icon: user-ninja, url: "https://www.abaltra.me"} 
  - {title: Mail, icon: envelope, url: "mailto:abaltra@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/abaltra"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: Twitter, icon: hashtag, url: "https://www.twitter.com/alejandrobaltra"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
